// Code generated by ent, DO NOT EDIT.

package recommendationspsapplications

import (
	"recruit/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldID, id))
}

// ApplicationID applies equality check predicate on the "ApplicationID" field. It's identical to ApplicationIDEQ.
func ApplicationID(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldApplicationID, v))
}

// EmployeeID applies equality check predicate on the "EmployeeID" field. It's identical to EmployeeIDEQ.
func EmployeeID(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldEmployeeID, v))
}

// ExamNameCode applies equality check predicate on the "ExamNameCode" field. It's identical to ExamNameCodeEQ.
func ExamNameCode(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldExamNameCode, v))
}

// ExamYear applies equality check predicate on the "ExamYear" field. It's identical to ExamYearEQ.
func ExamYear(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldExamYear, v))
}

// VacancyYear applies equality check predicate on the "VacancyYear" field. It's identical to VacancyYearEQ.
func VacancyYear(v int32) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldVacancyYear, v))
}

// CARecommendations applies equality check predicate on the "CA_Recommendations" field. It's identical to CARecommendationsEQ.
func CARecommendations(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldCARecommendations, v))
}

// CAUpdatedAt applies equality check predicate on the "CA_UpdatedAt" field. It's identical to CAUpdatedAtEQ.
func CAUpdatedAt(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldCAUpdatedAt, v))
}

// CAUserName applies equality check predicate on the "CA_UserName" field. It's identical to CAUserNameEQ.
func CAUserName(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldCAUserName, v))
}

// CARemarks applies equality check predicate on the "CA_Remarks" field. It's identical to CARemarksEQ.
func CARemarks(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldCARemarks, v))
}

// NORecommendations applies equality check predicate on the "NO_Recommendations" field. It's identical to NORecommendationsEQ.
func NORecommendations(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldNORecommendations, v))
}

// NOUpdatedAt applies equality check predicate on the "NO_UpdatedAt" field. It's identical to NOUpdatedAtEQ.
func NOUpdatedAt(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldNOUpdatedAt, v))
}

// NOUserName applies equality check predicate on the "NO_UserName" field. It's identical to NOUserNameEQ.
func NOUserName(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldNOUserName, v))
}

// NORemarks applies equality check predicate on the "NO_Remarks" field. It's identical to NORemarksEQ.
func NORemarks(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldNORemarks, v))
}

// ApplicationStatus applies equality check predicate on the "ApplicationStatus" field. It's identical to ApplicationStatusEQ.
func ApplicationStatus(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldApplicationStatus, v))
}

// UpdatedAt applies equality check predicate on the "UpdatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedBy applies equality check predicate on the "UpdatedBy" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldUpdatedBy, v))
}

// GenerateHallTicketFlag applies equality check predicate on the "GenerateHallTicketFlag" field. It's identical to GenerateHallTicketFlagEQ.
func GenerateHallTicketFlag(v bool) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldGenerateHallTicketFlag, v))
}

// ApplicationIDEQ applies the EQ predicate on the "ApplicationID" field.
func ApplicationIDEQ(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "ApplicationID" field.
func ApplicationIDNEQ(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "ApplicationID" field.
func ApplicationIDIn(vs ...int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "ApplicationID" field.
func ApplicationIDNotIn(vs ...int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldApplicationID, vs...))
}

// ApplicationIDGT applies the GT predicate on the "ApplicationID" field.
func ApplicationIDGT(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldApplicationID, v))
}

// ApplicationIDGTE applies the GTE predicate on the "ApplicationID" field.
func ApplicationIDGTE(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldApplicationID, v))
}

// ApplicationIDLT applies the LT predicate on the "ApplicationID" field.
func ApplicationIDLT(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldApplicationID, v))
}

// ApplicationIDLTE applies the LTE predicate on the "ApplicationID" field.
func ApplicationIDLTE(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldApplicationID, v))
}

// ApplicationIDIsNil applies the IsNil predicate on the "ApplicationID" field.
func ApplicationIDIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldApplicationID))
}

// ApplicationIDNotNil applies the NotNil predicate on the "ApplicationID" field.
func ApplicationIDNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldApplicationID))
}

// EmployeeIDEQ applies the EQ predicate on the "EmployeeID" field.
func EmployeeIDEQ(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldEmployeeID, v))
}

// EmployeeIDNEQ applies the NEQ predicate on the "EmployeeID" field.
func EmployeeIDNEQ(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldEmployeeID, v))
}

// EmployeeIDIn applies the In predicate on the "EmployeeID" field.
func EmployeeIDIn(vs ...int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldEmployeeID, vs...))
}

// EmployeeIDNotIn applies the NotIn predicate on the "EmployeeID" field.
func EmployeeIDNotIn(vs ...int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldEmployeeID, vs...))
}

// EmployeeIDGT applies the GT predicate on the "EmployeeID" field.
func EmployeeIDGT(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldEmployeeID, v))
}

// EmployeeIDGTE applies the GTE predicate on the "EmployeeID" field.
func EmployeeIDGTE(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldEmployeeID, v))
}

// EmployeeIDLT applies the LT predicate on the "EmployeeID" field.
func EmployeeIDLT(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldEmployeeID, v))
}

// EmployeeIDLTE applies the LTE predicate on the "EmployeeID" field.
func EmployeeIDLTE(v int64) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldEmployeeID, v))
}

// EmployeeIDIsNil applies the IsNil predicate on the "EmployeeID" field.
func EmployeeIDIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldEmployeeID))
}

// EmployeeIDNotNil applies the NotNil predicate on the "EmployeeID" field.
func EmployeeIDNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldEmployeeID))
}

// ExamNameCodeEQ applies the EQ predicate on the "ExamNameCode" field.
func ExamNameCodeEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldExamNameCode, v))
}

// ExamNameCodeNEQ applies the NEQ predicate on the "ExamNameCode" field.
func ExamNameCodeNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldExamNameCode, v))
}

// ExamNameCodeIn applies the In predicate on the "ExamNameCode" field.
func ExamNameCodeIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldExamNameCode, vs...))
}

// ExamNameCodeNotIn applies the NotIn predicate on the "ExamNameCode" field.
func ExamNameCodeNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldExamNameCode, vs...))
}

// ExamNameCodeGT applies the GT predicate on the "ExamNameCode" field.
func ExamNameCodeGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldExamNameCode, v))
}

// ExamNameCodeGTE applies the GTE predicate on the "ExamNameCode" field.
func ExamNameCodeGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldExamNameCode, v))
}

// ExamNameCodeLT applies the LT predicate on the "ExamNameCode" field.
func ExamNameCodeLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldExamNameCode, v))
}

// ExamNameCodeLTE applies the LTE predicate on the "ExamNameCode" field.
func ExamNameCodeLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldExamNameCode, v))
}

// ExamNameCodeContains applies the Contains predicate on the "ExamNameCode" field.
func ExamNameCodeContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldExamNameCode, v))
}

// ExamNameCodeHasPrefix applies the HasPrefix predicate on the "ExamNameCode" field.
func ExamNameCodeHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldExamNameCode, v))
}

// ExamNameCodeHasSuffix applies the HasSuffix predicate on the "ExamNameCode" field.
func ExamNameCodeHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldExamNameCode, v))
}

// ExamNameCodeIsNil applies the IsNil predicate on the "ExamNameCode" field.
func ExamNameCodeIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldExamNameCode))
}

// ExamNameCodeNotNil applies the NotNil predicate on the "ExamNameCode" field.
func ExamNameCodeNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldExamNameCode))
}

// ExamNameCodeEqualFold applies the EqualFold predicate on the "ExamNameCode" field.
func ExamNameCodeEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldExamNameCode, v))
}

// ExamNameCodeContainsFold applies the ContainsFold predicate on the "ExamNameCode" field.
func ExamNameCodeContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldExamNameCode, v))
}

// ExamYearEQ applies the EQ predicate on the "ExamYear" field.
func ExamYearEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldExamYear, v))
}

// ExamYearNEQ applies the NEQ predicate on the "ExamYear" field.
func ExamYearNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldExamYear, v))
}

// ExamYearIn applies the In predicate on the "ExamYear" field.
func ExamYearIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldExamYear, vs...))
}

// ExamYearNotIn applies the NotIn predicate on the "ExamYear" field.
func ExamYearNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldExamYear, vs...))
}

// ExamYearGT applies the GT predicate on the "ExamYear" field.
func ExamYearGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldExamYear, v))
}

// ExamYearGTE applies the GTE predicate on the "ExamYear" field.
func ExamYearGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldExamYear, v))
}

// ExamYearLT applies the LT predicate on the "ExamYear" field.
func ExamYearLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldExamYear, v))
}

// ExamYearLTE applies the LTE predicate on the "ExamYear" field.
func ExamYearLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldExamYear, v))
}

// ExamYearContains applies the Contains predicate on the "ExamYear" field.
func ExamYearContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldExamYear, v))
}

// ExamYearHasPrefix applies the HasPrefix predicate on the "ExamYear" field.
func ExamYearHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldExamYear, v))
}

// ExamYearHasSuffix applies the HasSuffix predicate on the "ExamYear" field.
func ExamYearHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldExamYear, v))
}

// ExamYearIsNil applies the IsNil predicate on the "ExamYear" field.
func ExamYearIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldExamYear))
}

// ExamYearNotNil applies the NotNil predicate on the "ExamYear" field.
func ExamYearNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldExamYear))
}

// ExamYearEqualFold applies the EqualFold predicate on the "ExamYear" field.
func ExamYearEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldExamYear, v))
}

// ExamYearContainsFold applies the ContainsFold predicate on the "ExamYear" field.
func ExamYearContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldExamYear, v))
}

// VacancyYearEQ applies the EQ predicate on the "VacancyYear" field.
func VacancyYearEQ(v int32) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldVacancyYear, v))
}

// VacancyYearNEQ applies the NEQ predicate on the "VacancyYear" field.
func VacancyYearNEQ(v int32) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldVacancyYear, v))
}

// VacancyYearIn applies the In predicate on the "VacancyYear" field.
func VacancyYearIn(vs ...int32) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldVacancyYear, vs...))
}

// VacancyYearNotIn applies the NotIn predicate on the "VacancyYear" field.
func VacancyYearNotIn(vs ...int32) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldVacancyYear, vs...))
}

// VacancyYearGT applies the GT predicate on the "VacancyYear" field.
func VacancyYearGT(v int32) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldVacancyYear, v))
}

// VacancyYearGTE applies the GTE predicate on the "VacancyYear" field.
func VacancyYearGTE(v int32) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldVacancyYear, v))
}

// VacancyYearLT applies the LT predicate on the "VacancyYear" field.
func VacancyYearLT(v int32) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldVacancyYear, v))
}

// VacancyYearLTE applies the LTE predicate on the "VacancyYear" field.
func VacancyYearLTE(v int32) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldVacancyYear, v))
}

// VacancyYearIsNil applies the IsNil predicate on the "VacancyYear" field.
func VacancyYearIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldVacancyYear))
}

// VacancyYearNotNil applies the NotNil predicate on the "VacancyYear" field.
func VacancyYearNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldVacancyYear))
}

// CARecommendationsEQ applies the EQ predicate on the "CA_Recommendations" field.
func CARecommendationsEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldCARecommendations, v))
}

// CARecommendationsNEQ applies the NEQ predicate on the "CA_Recommendations" field.
func CARecommendationsNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldCARecommendations, v))
}

// CARecommendationsIn applies the In predicate on the "CA_Recommendations" field.
func CARecommendationsIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldCARecommendations, vs...))
}

// CARecommendationsNotIn applies the NotIn predicate on the "CA_Recommendations" field.
func CARecommendationsNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldCARecommendations, vs...))
}

// CARecommendationsGT applies the GT predicate on the "CA_Recommendations" field.
func CARecommendationsGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldCARecommendations, v))
}

// CARecommendationsGTE applies the GTE predicate on the "CA_Recommendations" field.
func CARecommendationsGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldCARecommendations, v))
}

// CARecommendationsLT applies the LT predicate on the "CA_Recommendations" field.
func CARecommendationsLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldCARecommendations, v))
}

// CARecommendationsLTE applies the LTE predicate on the "CA_Recommendations" field.
func CARecommendationsLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldCARecommendations, v))
}

// CARecommendationsContains applies the Contains predicate on the "CA_Recommendations" field.
func CARecommendationsContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldCARecommendations, v))
}

// CARecommendationsHasPrefix applies the HasPrefix predicate on the "CA_Recommendations" field.
func CARecommendationsHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldCARecommendations, v))
}

// CARecommendationsHasSuffix applies the HasSuffix predicate on the "CA_Recommendations" field.
func CARecommendationsHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldCARecommendations, v))
}

// CARecommendationsIsNil applies the IsNil predicate on the "CA_Recommendations" field.
func CARecommendationsIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldCARecommendations))
}

// CARecommendationsNotNil applies the NotNil predicate on the "CA_Recommendations" field.
func CARecommendationsNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldCARecommendations))
}

// CARecommendationsEqualFold applies the EqualFold predicate on the "CA_Recommendations" field.
func CARecommendationsEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldCARecommendations, v))
}

// CARecommendationsContainsFold applies the ContainsFold predicate on the "CA_Recommendations" field.
func CARecommendationsContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldCARecommendations, v))
}

// CAUpdatedAtEQ applies the EQ predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtEQ(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldCAUpdatedAt, v))
}

// CAUpdatedAtNEQ applies the NEQ predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtNEQ(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldCAUpdatedAt, v))
}

// CAUpdatedAtIn applies the In predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtIn(vs ...time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldCAUpdatedAt, vs...))
}

// CAUpdatedAtNotIn applies the NotIn predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtNotIn(vs ...time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldCAUpdatedAt, vs...))
}

// CAUpdatedAtGT applies the GT predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtGT(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldCAUpdatedAt, v))
}

// CAUpdatedAtGTE applies the GTE predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtGTE(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldCAUpdatedAt, v))
}

// CAUpdatedAtLT applies the LT predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtLT(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldCAUpdatedAt, v))
}

// CAUpdatedAtLTE applies the LTE predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtLTE(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldCAUpdatedAt, v))
}

// CAUpdatedAtIsNil applies the IsNil predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldCAUpdatedAt))
}

// CAUpdatedAtNotNil applies the NotNil predicate on the "CA_UpdatedAt" field.
func CAUpdatedAtNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldCAUpdatedAt))
}

// CAUserNameEQ applies the EQ predicate on the "CA_UserName" field.
func CAUserNameEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldCAUserName, v))
}

// CAUserNameNEQ applies the NEQ predicate on the "CA_UserName" field.
func CAUserNameNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldCAUserName, v))
}

// CAUserNameIn applies the In predicate on the "CA_UserName" field.
func CAUserNameIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldCAUserName, vs...))
}

// CAUserNameNotIn applies the NotIn predicate on the "CA_UserName" field.
func CAUserNameNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldCAUserName, vs...))
}

// CAUserNameGT applies the GT predicate on the "CA_UserName" field.
func CAUserNameGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldCAUserName, v))
}

// CAUserNameGTE applies the GTE predicate on the "CA_UserName" field.
func CAUserNameGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldCAUserName, v))
}

// CAUserNameLT applies the LT predicate on the "CA_UserName" field.
func CAUserNameLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldCAUserName, v))
}

// CAUserNameLTE applies the LTE predicate on the "CA_UserName" field.
func CAUserNameLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldCAUserName, v))
}

// CAUserNameContains applies the Contains predicate on the "CA_UserName" field.
func CAUserNameContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldCAUserName, v))
}

// CAUserNameHasPrefix applies the HasPrefix predicate on the "CA_UserName" field.
func CAUserNameHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldCAUserName, v))
}

// CAUserNameHasSuffix applies the HasSuffix predicate on the "CA_UserName" field.
func CAUserNameHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldCAUserName, v))
}

// CAUserNameIsNil applies the IsNil predicate on the "CA_UserName" field.
func CAUserNameIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldCAUserName))
}

// CAUserNameNotNil applies the NotNil predicate on the "CA_UserName" field.
func CAUserNameNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldCAUserName))
}

// CAUserNameEqualFold applies the EqualFold predicate on the "CA_UserName" field.
func CAUserNameEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldCAUserName, v))
}

// CAUserNameContainsFold applies the ContainsFold predicate on the "CA_UserName" field.
func CAUserNameContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldCAUserName, v))
}

// CARemarksEQ applies the EQ predicate on the "CA_Remarks" field.
func CARemarksEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldCARemarks, v))
}

// CARemarksNEQ applies the NEQ predicate on the "CA_Remarks" field.
func CARemarksNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldCARemarks, v))
}

// CARemarksIn applies the In predicate on the "CA_Remarks" field.
func CARemarksIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldCARemarks, vs...))
}

// CARemarksNotIn applies the NotIn predicate on the "CA_Remarks" field.
func CARemarksNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldCARemarks, vs...))
}

// CARemarksGT applies the GT predicate on the "CA_Remarks" field.
func CARemarksGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldCARemarks, v))
}

// CARemarksGTE applies the GTE predicate on the "CA_Remarks" field.
func CARemarksGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldCARemarks, v))
}

// CARemarksLT applies the LT predicate on the "CA_Remarks" field.
func CARemarksLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldCARemarks, v))
}

// CARemarksLTE applies the LTE predicate on the "CA_Remarks" field.
func CARemarksLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldCARemarks, v))
}

// CARemarksContains applies the Contains predicate on the "CA_Remarks" field.
func CARemarksContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldCARemarks, v))
}

// CARemarksHasPrefix applies the HasPrefix predicate on the "CA_Remarks" field.
func CARemarksHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldCARemarks, v))
}

// CARemarksHasSuffix applies the HasSuffix predicate on the "CA_Remarks" field.
func CARemarksHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldCARemarks, v))
}

// CARemarksIsNil applies the IsNil predicate on the "CA_Remarks" field.
func CARemarksIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldCARemarks))
}

// CARemarksNotNil applies the NotNil predicate on the "CA_Remarks" field.
func CARemarksNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldCARemarks))
}

// CARemarksEqualFold applies the EqualFold predicate on the "CA_Remarks" field.
func CARemarksEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldCARemarks, v))
}

// CARemarksContainsFold applies the ContainsFold predicate on the "CA_Remarks" field.
func CARemarksContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldCARemarks, v))
}

// NORecommendationsEQ applies the EQ predicate on the "NO_Recommendations" field.
func NORecommendationsEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldNORecommendations, v))
}

// NORecommendationsNEQ applies the NEQ predicate on the "NO_Recommendations" field.
func NORecommendationsNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldNORecommendations, v))
}

// NORecommendationsIn applies the In predicate on the "NO_Recommendations" field.
func NORecommendationsIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldNORecommendations, vs...))
}

// NORecommendationsNotIn applies the NotIn predicate on the "NO_Recommendations" field.
func NORecommendationsNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldNORecommendations, vs...))
}

// NORecommendationsGT applies the GT predicate on the "NO_Recommendations" field.
func NORecommendationsGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldNORecommendations, v))
}

// NORecommendationsGTE applies the GTE predicate on the "NO_Recommendations" field.
func NORecommendationsGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldNORecommendations, v))
}

// NORecommendationsLT applies the LT predicate on the "NO_Recommendations" field.
func NORecommendationsLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldNORecommendations, v))
}

// NORecommendationsLTE applies the LTE predicate on the "NO_Recommendations" field.
func NORecommendationsLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldNORecommendations, v))
}

// NORecommendationsContains applies the Contains predicate on the "NO_Recommendations" field.
func NORecommendationsContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldNORecommendations, v))
}

// NORecommendationsHasPrefix applies the HasPrefix predicate on the "NO_Recommendations" field.
func NORecommendationsHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldNORecommendations, v))
}

// NORecommendationsHasSuffix applies the HasSuffix predicate on the "NO_Recommendations" field.
func NORecommendationsHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldNORecommendations, v))
}

// NORecommendationsIsNil applies the IsNil predicate on the "NO_Recommendations" field.
func NORecommendationsIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldNORecommendations))
}

// NORecommendationsNotNil applies the NotNil predicate on the "NO_Recommendations" field.
func NORecommendationsNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldNORecommendations))
}

// NORecommendationsEqualFold applies the EqualFold predicate on the "NO_Recommendations" field.
func NORecommendationsEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldNORecommendations, v))
}

// NORecommendationsContainsFold applies the ContainsFold predicate on the "NO_Recommendations" field.
func NORecommendationsContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldNORecommendations, v))
}

// NOUpdatedAtEQ applies the EQ predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtEQ(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldNOUpdatedAt, v))
}

// NOUpdatedAtNEQ applies the NEQ predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtNEQ(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldNOUpdatedAt, v))
}

// NOUpdatedAtIn applies the In predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtIn(vs ...time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldNOUpdatedAt, vs...))
}

// NOUpdatedAtNotIn applies the NotIn predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtNotIn(vs ...time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldNOUpdatedAt, vs...))
}

// NOUpdatedAtGT applies the GT predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtGT(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldNOUpdatedAt, v))
}

// NOUpdatedAtGTE applies the GTE predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtGTE(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldNOUpdatedAt, v))
}

// NOUpdatedAtLT applies the LT predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtLT(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldNOUpdatedAt, v))
}

// NOUpdatedAtLTE applies the LTE predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtLTE(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldNOUpdatedAt, v))
}

// NOUpdatedAtIsNil applies the IsNil predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldNOUpdatedAt))
}

// NOUpdatedAtNotNil applies the NotNil predicate on the "NO_UpdatedAt" field.
func NOUpdatedAtNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldNOUpdatedAt))
}

// NOUserNameEQ applies the EQ predicate on the "NO_UserName" field.
func NOUserNameEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldNOUserName, v))
}

// NOUserNameNEQ applies the NEQ predicate on the "NO_UserName" field.
func NOUserNameNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldNOUserName, v))
}

// NOUserNameIn applies the In predicate on the "NO_UserName" field.
func NOUserNameIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldNOUserName, vs...))
}

// NOUserNameNotIn applies the NotIn predicate on the "NO_UserName" field.
func NOUserNameNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldNOUserName, vs...))
}

// NOUserNameGT applies the GT predicate on the "NO_UserName" field.
func NOUserNameGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldNOUserName, v))
}

// NOUserNameGTE applies the GTE predicate on the "NO_UserName" field.
func NOUserNameGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldNOUserName, v))
}

// NOUserNameLT applies the LT predicate on the "NO_UserName" field.
func NOUserNameLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldNOUserName, v))
}

// NOUserNameLTE applies the LTE predicate on the "NO_UserName" field.
func NOUserNameLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldNOUserName, v))
}

// NOUserNameContains applies the Contains predicate on the "NO_UserName" field.
func NOUserNameContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldNOUserName, v))
}

// NOUserNameHasPrefix applies the HasPrefix predicate on the "NO_UserName" field.
func NOUserNameHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldNOUserName, v))
}

// NOUserNameHasSuffix applies the HasSuffix predicate on the "NO_UserName" field.
func NOUserNameHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldNOUserName, v))
}

// NOUserNameIsNil applies the IsNil predicate on the "NO_UserName" field.
func NOUserNameIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldNOUserName))
}

// NOUserNameNotNil applies the NotNil predicate on the "NO_UserName" field.
func NOUserNameNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldNOUserName))
}

// NOUserNameEqualFold applies the EqualFold predicate on the "NO_UserName" field.
func NOUserNameEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldNOUserName, v))
}

// NOUserNameContainsFold applies the ContainsFold predicate on the "NO_UserName" field.
func NOUserNameContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldNOUserName, v))
}

// NORemarksEQ applies the EQ predicate on the "NO_Remarks" field.
func NORemarksEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldNORemarks, v))
}

// NORemarksNEQ applies the NEQ predicate on the "NO_Remarks" field.
func NORemarksNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldNORemarks, v))
}

// NORemarksIn applies the In predicate on the "NO_Remarks" field.
func NORemarksIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldNORemarks, vs...))
}

// NORemarksNotIn applies the NotIn predicate on the "NO_Remarks" field.
func NORemarksNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldNORemarks, vs...))
}

// NORemarksGT applies the GT predicate on the "NO_Remarks" field.
func NORemarksGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldNORemarks, v))
}

// NORemarksGTE applies the GTE predicate on the "NO_Remarks" field.
func NORemarksGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldNORemarks, v))
}

// NORemarksLT applies the LT predicate on the "NO_Remarks" field.
func NORemarksLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldNORemarks, v))
}

// NORemarksLTE applies the LTE predicate on the "NO_Remarks" field.
func NORemarksLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldNORemarks, v))
}

// NORemarksContains applies the Contains predicate on the "NO_Remarks" field.
func NORemarksContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldNORemarks, v))
}

// NORemarksHasPrefix applies the HasPrefix predicate on the "NO_Remarks" field.
func NORemarksHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldNORemarks, v))
}

// NORemarksHasSuffix applies the HasSuffix predicate on the "NO_Remarks" field.
func NORemarksHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldNORemarks, v))
}

// NORemarksIsNil applies the IsNil predicate on the "NO_Remarks" field.
func NORemarksIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldNORemarks))
}

// NORemarksNotNil applies the NotNil predicate on the "NO_Remarks" field.
func NORemarksNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldNORemarks))
}

// NORemarksEqualFold applies the EqualFold predicate on the "NO_Remarks" field.
func NORemarksEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldNORemarks, v))
}

// NORemarksContainsFold applies the ContainsFold predicate on the "NO_Remarks" field.
func NORemarksContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldNORemarks, v))
}

// ApplicationStatusEQ applies the EQ predicate on the "ApplicationStatus" field.
func ApplicationStatusEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldApplicationStatus, v))
}

// ApplicationStatusNEQ applies the NEQ predicate on the "ApplicationStatus" field.
func ApplicationStatusNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldApplicationStatus, v))
}

// ApplicationStatusIn applies the In predicate on the "ApplicationStatus" field.
func ApplicationStatusIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldApplicationStatus, vs...))
}

// ApplicationStatusNotIn applies the NotIn predicate on the "ApplicationStatus" field.
func ApplicationStatusNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldApplicationStatus, vs...))
}

// ApplicationStatusGT applies the GT predicate on the "ApplicationStatus" field.
func ApplicationStatusGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldApplicationStatus, v))
}

// ApplicationStatusGTE applies the GTE predicate on the "ApplicationStatus" field.
func ApplicationStatusGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldApplicationStatus, v))
}

// ApplicationStatusLT applies the LT predicate on the "ApplicationStatus" field.
func ApplicationStatusLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldApplicationStatus, v))
}

// ApplicationStatusLTE applies the LTE predicate on the "ApplicationStatus" field.
func ApplicationStatusLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldApplicationStatus, v))
}

// ApplicationStatusContains applies the Contains predicate on the "ApplicationStatus" field.
func ApplicationStatusContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldApplicationStatus, v))
}

// ApplicationStatusHasPrefix applies the HasPrefix predicate on the "ApplicationStatus" field.
func ApplicationStatusHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldApplicationStatus, v))
}

// ApplicationStatusHasSuffix applies the HasSuffix predicate on the "ApplicationStatus" field.
func ApplicationStatusHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldApplicationStatus, v))
}

// ApplicationStatusIsNil applies the IsNil predicate on the "ApplicationStatus" field.
func ApplicationStatusIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldApplicationStatus))
}

// ApplicationStatusNotNil applies the NotNil predicate on the "ApplicationStatus" field.
func ApplicationStatusNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldApplicationStatus))
}

// ApplicationStatusEqualFold applies the EqualFold predicate on the "ApplicationStatus" field.
func ApplicationStatusEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldApplicationStatus, v))
}

// ApplicationStatusContainsFold applies the ContainsFold predicate on the "ApplicationStatus" field.
func ApplicationStatusContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldApplicationStatus, v))
}

// UpdatedAtEQ applies the EQ predicate on the "UpdatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "UpdatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "UpdatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "UpdatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "UpdatedAt" field.
func UpdatedAtGT(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "UpdatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "UpdatedAt" field.
func UpdatedAtLT(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "UpdatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "UpdatedAt" field.
func UpdatedAtIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "UpdatedAt" field.
func UpdatedAtNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldUpdatedAt))
}

// UpdatedByEQ applies the EQ predicate on the "UpdatedBy" field.
func UpdatedByEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "UpdatedBy" field.
func UpdatedByNEQ(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "UpdatedBy" field.
func UpdatedByIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "UpdatedBy" field.
func UpdatedByNotIn(vs ...string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "UpdatedBy" field.
func UpdatedByGT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "UpdatedBy" field.
func UpdatedByGTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "UpdatedBy" field.
func UpdatedByLT(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "UpdatedBy" field.
func UpdatedByLTE(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "UpdatedBy" field.
func UpdatedByContains(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "UpdatedBy" field.
func UpdatedByHasPrefix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "UpdatedBy" field.
func UpdatedByHasSuffix(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "UpdatedBy" field.
func UpdatedByIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "UpdatedBy" field.
func UpdatedByNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "UpdatedBy" field.
func UpdatedByEqualFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "UpdatedBy" field.
func UpdatedByContainsFold(v string) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// GenerateHallTicketFlagEQ applies the EQ predicate on the "GenerateHallTicketFlag" field.
func GenerateHallTicketFlagEQ(v bool) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldEQ(FieldGenerateHallTicketFlag, v))
}

// GenerateHallTicketFlagNEQ applies the NEQ predicate on the "GenerateHallTicketFlag" field.
func GenerateHallTicketFlagNEQ(v bool) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNEQ(FieldGenerateHallTicketFlag, v))
}

// GenerateHallTicketFlagIsNil applies the IsNil predicate on the "GenerateHallTicketFlag" field.
func GenerateHallTicketFlagIsNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldIsNull(FieldGenerateHallTicketFlag))
}

// GenerateHallTicketFlagNotNil applies the NotNil predicate on the "GenerateHallTicketFlag" field.
func GenerateHallTicketFlagNotNil() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(sql.FieldNotNull(FieldGenerateHallTicketFlag))
}

// HasApplnRefPS applies the HasEdge predicate on the "ApplnRefPS" edge.
func HasApplnRefPS() predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ApplnRefPSTable, ApplnRefPSColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplnRefPSWith applies the HasEdge predicate on the "ApplnRefPS" edge with a given conditions (other predicates).
func HasApplnRefPSWith(preds ...predicate.Exam_Applications_PS) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(func(s *sql.Selector) {
		step := newApplnRefPSStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RecommendationsPSApplications) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RecommendationsPSApplications) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RecommendationsPSApplications) predicate.RecommendationsPSApplications {
	return predicate.RecommendationsPSApplications(func(s *sql.Selector) {
		p(s.Not())
	})
}
