// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"recruit/ent/ageeligibility"
	"recruit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgeEligibilityQuery is the builder for querying AgeEligibility entities.
type AgeEligibilityQuery struct {
	config
	ctx        *QueryContext
	order      []ageeligibility.OrderOption
	inters     []Interceptor
	predicates []predicate.AgeEligibility
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AgeEligibilityQuery builder.
func (aeq *AgeEligibilityQuery) Where(ps ...predicate.AgeEligibility) *AgeEligibilityQuery {
	aeq.predicates = append(aeq.predicates, ps...)
	return aeq
}

// Limit the number of records to be returned by this query.
func (aeq *AgeEligibilityQuery) Limit(limit int) *AgeEligibilityQuery {
	aeq.ctx.Limit = &limit
	return aeq
}

// Offset to start from.
func (aeq *AgeEligibilityQuery) Offset(offset int) *AgeEligibilityQuery {
	aeq.ctx.Offset = &offset
	return aeq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aeq *AgeEligibilityQuery) Unique(unique bool) *AgeEligibilityQuery {
	aeq.ctx.Unique = &unique
	return aeq
}

// Order specifies how the records should be ordered.
func (aeq *AgeEligibilityQuery) Order(o ...ageeligibility.OrderOption) *AgeEligibilityQuery {
	aeq.order = append(aeq.order, o...)
	return aeq
}

// First returns the first AgeEligibility entity from the query.
// Returns a *NotFoundError when no AgeEligibility was found.
func (aeq *AgeEligibilityQuery) First(ctx context.Context) (*AgeEligibility, error) {
	nodes, err := aeq.Limit(1).All(setContextOp(ctx, aeq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ageeligibility.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aeq *AgeEligibilityQuery) FirstX(ctx context.Context) *AgeEligibility {
	node, err := aeq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AgeEligibility ID from the query.
// Returns a *NotFoundError when no AgeEligibility ID was found.
func (aeq *AgeEligibilityQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = aeq.Limit(1).IDs(setContextOp(ctx, aeq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ageeligibility.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aeq *AgeEligibilityQuery) FirstIDX(ctx context.Context) int32 {
	id, err := aeq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AgeEligibility entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AgeEligibility entity is found.
// Returns a *NotFoundError when no AgeEligibility entities are found.
func (aeq *AgeEligibilityQuery) Only(ctx context.Context) (*AgeEligibility, error) {
	nodes, err := aeq.Limit(2).All(setContextOp(ctx, aeq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ageeligibility.Label}
	default:
		return nil, &NotSingularError{ageeligibility.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aeq *AgeEligibilityQuery) OnlyX(ctx context.Context) *AgeEligibility {
	node, err := aeq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AgeEligibility ID in the query.
// Returns a *NotSingularError when more than one AgeEligibility ID is found.
// Returns a *NotFoundError when no entities are found.
func (aeq *AgeEligibilityQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = aeq.Limit(2).IDs(setContextOp(ctx, aeq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ageeligibility.Label}
	default:
		err = &NotSingularError{ageeligibility.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aeq *AgeEligibilityQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := aeq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AgeEligibilities.
func (aeq *AgeEligibilityQuery) All(ctx context.Context) ([]*AgeEligibility, error) {
	ctx = setContextOp(ctx, aeq.ctx, "All")
	if err := aeq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AgeEligibility, *AgeEligibilityQuery]()
	return withInterceptors[[]*AgeEligibility](ctx, aeq, qr, aeq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aeq *AgeEligibilityQuery) AllX(ctx context.Context) []*AgeEligibility {
	nodes, err := aeq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AgeEligibility IDs.
func (aeq *AgeEligibilityQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if aeq.ctx.Unique == nil && aeq.path != nil {
		aeq.Unique(true)
	}
	ctx = setContextOp(ctx, aeq.ctx, "IDs")
	if err = aeq.Select(ageeligibility.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aeq *AgeEligibilityQuery) IDsX(ctx context.Context) []int32 {
	ids, err := aeq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aeq *AgeEligibilityQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aeq.ctx, "Count")
	if err := aeq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aeq, querierCount[*AgeEligibilityQuery](), aeq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aeq *AgeEligibilityQuery) CountX(ctx context.Context) int {
	count, err := aeq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aeq *AgeEligibilityQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aeq.ctx, "Exist")
	switch _, err := aeq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aeq *AgeEligibilityQuery) ExistX(ctx context.Context) bool {
	exist, err := aeq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AgeEligibilityQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aeq *AgeEligibilityQuery) Clone() *AgeEligibilityQuery {
	if aeq == nil {
		return nil
	}
	return &AgeEligibilityQuery{
		config:     aeq.config,
		ctx:        aeq.ctx.Clone(),
		order:      append([]ageeligibility.OrderOption{}, aeq.order...),
		inters:     append([]Interceptor{}, aeq.inters...),
		predicates: append([]predicate.AgeEligibility{}, aeq.predicates...),
		// clone intermediate query.
		sql:  aeq.sql.Clone(),
		path: aeq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		EligibillityCode int32 `json:"EligibillityCode,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AgeEligibility.Query().
//		GroupBy(ageeligibility.FieldEligibillityCode).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aeq *AgeEligibilityQuery) GroupBy(field string, fields ...string) *AgeEligibilityGroupBy {
	aeq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AgeEligibilityGroupBy{build: aeq}
	grbuild.flds = &aeq.ctx.Fields
	grbuild.label = ageeligibility.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		EligibillityCode int32 `json:"EligibillityCode,omitempty"`
//	}
//
//	client.AgeEligibility.Query().
//		Select(ageeligibility.FieldEligibillityCode).
//		Scan(ctx, &v)
func (aeq *AgeEligibilityQuery) Select(fields ...string) *AgeEligibilitySelect {
	aeq.ctx.Fields = append(aeq.ctx.Fields, fields...)
	sbuild := &AgeEligibilitySelect{AgeEligibilityQuery: aeq}
	sbuild.label = ageeligibility.Label
	sbuild.flds, sbuild.scan = &aeq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AgeEligibilitySelect configured with the given aggregations.
func (aeq *AgeEligibilityQuery) Aggregate(fns ...AggregateFunc) *AgeEligibilitySelect {
	return aeq.Select().Aggregate(fns...)
}

func (aeq *AgeEligibilityQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aeq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aeq); err != nil {
				return err
			}
		}
	}
	for _, f := range aeq.ctx.Fields {
		if !ageeligibility.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aeq.path != nil {
		prev, err := aeq.path(ctx)
		if err != nil {
			return err
		}
		aeq.sql = prev
	}
	return nil
}

func (aeq *AgeEligibilityQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AgeEligibility, error) {
	var (
		nodes = []*AgeEligibility{}
		_spec = aeq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AgeEligibility).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AgeEligibility{config: aeq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aeq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aeq *AgeEligibilityQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aeq.querySpec()
	_spec.Node.Columns = aeq.ctx.Fields
	if len(aeq.ctx.Fields) > 0 {
		_spec.Unique = aeq.ctx.Unique != nil && *aeq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aeq.driver, _spec)
}

func (aeq *AgeEligibilityQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ageeligibility.Table, ageeligibility.Columns, sqlgraph.NewFieldSpec(ageeligibility.FieldID, field.TypeInt32))
	_spec.From = aeq.sql
	if unique := aeq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aeq.path != nil {
		_spec.Unique = true
	}
	if fields := aeq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ageeligibility.FieldID)
		for i := range fields {
			if fields[i] != ageeligibility.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aeq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aeq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aeq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aeq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aeq *AgeEligibilityQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aeq.driver.Dialect())
	t1 := builder.Table(ageeligibility.Table)
	columns := aeq.ctx.Fields
	if len(columns) == 0 {
		columns = ageeligibility.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aeq.sql != nil {
		selector = aeq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aeq.ctx.Unique != nil && *aeq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aeq.predicates {
		p(selector)
	}
	for _, p := range aeq.order {
		p(selector)
	}
	if offset := aeq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aeq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AgeEligibilityGroupBy is the group-by builder for AgeEligibility entities.
type AgeEligibilityGroupBy struct {
	selector
	build *AgeEligibilityQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aegb *AgeEligibilityGroupBy) Aggregate(fns ...AggregateFunc) *AgeEligibilityGroupBy {
	aegb.fns = append(aegb.fns, fns...)
	return aegb
}

// Scan applies the selector query and scans the result into the given value.
func (aegb *AgeEligibilityGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aegb.build.ctx, "GroupBy")
	if err := aegb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgeEligibilityQuery, *AgeEligibilityGroupBy](ctx, aegb.build, aegb, aegb.build.inters, v)
}

func (aegb *AgeEligibilityGroupBy) sqlScan(ctx context.Context, root *AgeEligibilityQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(aegb.fns))
	for _, fn := range aegb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*aegb.flds)+len(aegb.fns))
		for _, f := range *aegb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*aegb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aegb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AgeEligibilitySelect is the builder for selecting fields of AgeEligibility entities.
type AgeEligibilitySelect struct {
	*AgeEligibilityQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (aes *AgeEligibilitySelect) Aggregate(fns ...AggregateFunc) *AgeEligibilitySelect {
	aes.fns = append(aes.fns, fns...)
	return aes
}

// Scan applies the selector query and scans the result into the given value.
func (aes *AgeEligibilitySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, aes.ctx, "Select")
	if err := aes.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgeEligibilityQuery, *AgeEligibilitySelect](ctx, aes.AgeEligibilityQuery, aes, aes.inters, v)
}

func (aes *AgeEligibilitySelect) sqlScan(ctx context.Context, root *AgeEligibilityQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(aes.fns))
	for _, fn := range aes.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*aes.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aes.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
