// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"recruit/ent/division_choice_pm"
	"recruit/ent/exam_applications_gdspm"
	"recruit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DivisionChoicePMQuery is the builder for querying Division_Choice_PM entities.
type DivisionChoicePMQuery struct {
	config
	ctx               *QueryContext
	order             []division_choice_pm.OrderOption
	inters            []Interceptor
	predicates        []predicate.Division_Choice_PM
	withApplnGDSPMRef *ExamApplicationsGDSPMQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DivisionChoicePMQuery builder.
func (dcpq *DivisionChoicePMQuery) Where(ps ...predicate.Division_Choice_PM) *DivisionChoicePMQuery {
	dcpq.predicates = append(dcpq.predicates, ps...)
	return dcpq
}

// Limit the number of records to be returned by this query.
func (dcpq *DivisionChoicePMQuery) Limit(limit int) *DivisionChoicePMQuery {
	dcpq.ctx.Limit = &limit
	return dcpq
}

// Offset to start from.
func (dcpq *DivisionChoicePMQuery) Offset(offset int) *DivisionChoicePMQuery {
	dcpq.ctx.Offset = &offset
	return dcpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dcpq *DivisionChoicePMQuery) Unique(unique bool) *DivisionChoicePMQuery {
	dcpq.ctx.Unique = &unique
	return dcpq
}

// Order specifies how the records should be ordered.
func (dcpq *DivisionChoicePMQuery) Order(o ...division_choice_pm.OrderOption) *DivisionChoicePMQuery {
	dcpq.order = append(dcpq.order, o...)
	return dcpq
}

// QueryApplnGDSPMRef chains the current query on the "ApplnGDSPM_Ref" edge.
func (dcpq *DivisionChoicePMQuery) QueryApplnGDSPMRef() *ExamApplicationsGDSPMQuery {
	query := (&ExamApplicationsGDSPMClient{config: dcpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dcpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dcpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(division_choice_pm.Table, division_choice_pm.FieldID, selector),
			sqlgraph.To(exam_applications_gdspm.Table, exam_applications_gdspm.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, division_choice_pm.ApplnGDSPMRefTable, division_choice_pm.ApplnGDSPMRefColumn),
		)
		fromU = sqlgraph.SetNeighbors(dcpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Division_Choice_PM entity from the query.
// Returns a *NotFoundError when no Division_Choice_PM was found.
func (dcpq *DivisionChoicePMQuery) First(ctx context.Context) (*Division_Choice_PM, error) {
	nodes, err := dcpq.Limit(1).All(setContextOp(ctx, dcpq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{division_choice_pm.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dcpq *DivisionChoicePMQuery) FirstX(ctx context.Context) *Division_Choice_PM {
	node, err := dcpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Division_Choice_PM ID from the query.
// Returns a *NotFoundError when no Division_Choice_PM ID was found.
func (dcpq *DivisionChoicePMQuery) FirstID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = dcpq.Limit(1).IDs(setContextOp(ctx, dcpq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{division_choice_pm.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dcpq *DivisionChoicePMQuery) FirstIDX(ctx context.Context) int32 {
	id, err := dcpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Division_Choice_PM entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Division_Choice_PM entity is found.
// Returns a *NotFoundError when no Division_Choice_PM entities are found.
func (dcpq *DivisionChoicePMQuery) Only(ctx context.Context) (*Division_Choice_PM, error) {
	nodes, err := dcpq.Limit(2).All(setContextOp(ctx, dcpq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{division_choice_pm.Label}
	default:
		return nil, &NotSingularError{division_choice_pm.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dcpq *DivisionChoicePMQuery) OnlyX(ctx context.Context) *Division_Choice_PM {
	node, err := dcpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Division_Choice_PM ID in the query.
// Returns a *NotSingularError when more than one Division_Choice_PM ID is found.
// Returns a *NotFoundError when no entities are found.
func (dcpq *DivisionChoicePMQuery) OnlyID(ctx context.Context) (id int32, err error) {
	var ids []int32
	if ids, err = dcpq.Limit(2).IDs(setContextOp(ctx, dcpq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{division_choice_pm.Label}
	default:
		err = &NotSingularError{division_choice_pm.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dcpq *DivisionChoicePMQuery) OnlyIDX(ctx context.Context) int32 {
	id, err := dcpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Division_Choice_PMs.
func (dcpq *DivisionChoicePMQuery) All(ctx context.Context) ([]*Division_Choice_PM, error) {
	ctx = setContextOp(ctx, dcpq.ctx, "All")
	if err := dcpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Division_Choice_PM, *DivisionChoicePMQuery]()
	return withInterceptors[[]*Division_Choice_PM](ctx, dcpq, qr, dcpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dcpq *DivisionChoicePMQuery) AllX(ctx context.Context) []*Division_Choice_PM {
	nodes, err := dcpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Division_Choice_PM IDs.
func (dcpq *DivisionChoicePMQuery) IDs(ctx context.Context) (ids []int32, err error) {
	if dcpq.ctx.Unique == nil && dcpq.path != nil {
		dcpq.Unique(true)
	}
	ctx = setContextOp(ctx, dcpq.ctx, "IDs")
	if err = dcpq.Select(division_choice_pm.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dcpq *DivisionChoicePMQuery) IDsX(ctx context.Context) []int32 {
	ids, err := dcpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dcpq *DivisionChoicePMQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dcpq.ctx, "Count")
	if err := dcpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dcpq, querierCount[*DivisionChoicePMQuery](), dcpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dcpq *DivisionChoicePMQuery) CountX(ctx context.Context) int {
	count, err := dcpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dcpq *DivisionChoicePMQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dcpq.ctx, "Exist")
	switch _, err := dcpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dcpq *DivisionChoicePMQuery) ExistX(ctx context.Context) bool {
	exist, err := dcpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DivisionChoicePMQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dcpq *DivisionChoicePMQuery) Clone() *DivisionChoicePMQuery {
	if dcpq == nil {
		return nil
	}
	return &DivisionChoicePMQuery{
		config:            dcpq.config,
		ctx:               dcpq.ctx.Clone(),
		order:             append([]division_choice_pm.OrderOption{}, dcpq.order...),
		inters:            append([]Interceptor{}, dcpq.inters...),
		predicates:        append([]predicate.Division_Choice_PM{}, dcpq.predicates...),
		withApplnGDSPMRef: dcpq.withApplnGDSPMRef.Clone(),
		// clone intermediate query.
		sql:  dcpq.sql.Clone(),
		path: dcpq.path,
	}
}

// WithApplnGDSPMRef tells the query-builder to eager-load the nodes that are connected to
// the "ApplnGDSPM_Ref" edge. The optional arguments are used to configure the query builder of the edge.
func (dcpq *DivisionChoicePMQuery) WithApplnGDSPMRef(opts ...func(*ExamApplicationsGDSPMQuery)) *DivisionChoicePMQuery {
	query := (&ExamApplicationsGDSPMClient{config: dcpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dcpq.withApplnGDSPMRef = query
	return dcpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ApplicationID int64 `json:"ApplicationID,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DivisionChoicePM.Query().
//		GroupBy(division_choice_pm.FieldApplicationID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dcpq *DivisionChoicePMQuery) GroupBy(field string, fields ...string) *DivisionChoicePMGroupBy {
	dcpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DivisionChoicePMGroupBy{build: dcpq}
	grbuild.flds = &dcpq.ctx.Fields
	grbuild.label = division_choice_pm.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ApplicationID int64 `json:"ApplicationID,omitempty"`
//	}
//
//	client.DivisionChoicePM.Query().
//		Select(division_choice_pm.FieldApplicationID).
//		Scan(ctx, &v)
func (dcpq *DivisionChoicePMQuery) Select(fields ...string) *DivisionChoicePMSelect {
	dcpq.ctx.Fields = append(dcpq.ctx.Fields, fields...)
	sbuild := &DivisionChoicePMSelect{DivisionChoicePMQuery: dcpq}
	sbuild.label = division_choice_pm.Label
	sbuild.flds, sbuild.scan = &dcpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DivisionChoicePMSelect configured with the given aggregations.
func (dcpq *DivisionChoicePMQuery) Aggregate(fns ...AggregateFunc) *DivisionChoicePMSelect {
	return dcpq.Select().Aggregate(fns...)
}

func (dcpq *DivisionChoicePMQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dcpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dcpq); err != nil {
				return err
			}
		}
	}
	for _, f := range dcpq.ctx.Fields {
		if !division_choice_pm.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dcpq.path != nil {
		prev, err := dcpq.path(ctx)
		if err != nil {
			return err
		}
		dcpq.sql = prev
	}
	return nil
}

func (dcpq *DivisionChoicePMQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Division_Choice_PM, error) {
	var (
		nodes       = []*Division_Choice_PM{}
		_spec       = dcpq.querySpec()
		loadedTypes = [1]bool{
			dcpq.withApplnGDSPMRef != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Division_Choice_PM).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Division_Choice_PM{config: dcpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dcpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dcpq.withApplnGDSPMRef; query != nil {
		if err := dcpq.loadApplnGDSPMRef(ctx, query, nodes, nil,
			func(n *Division_Choice_PM, e *Exam_Applications_GDSPM) { n.Edges.ApplnGDSPMRef = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dcpq *DivisionChoicePMQuery) loadApplnGDSPMRef(ctx context.Context, query *ExamApplicationsGDSPMQuery, nodes []*Division_Choice_PM, init func(*Division_Choice_PM), assign func(*Division_Choice_PM, *Exam_Applications_GDSPM)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*Division_Choice_PM)
	for i := range nodes {
		fk := nodes[i].ApplicationID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(exam_applications_gdspm.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ApplicationID" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dcpq *DivisionChoicePMQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dcpq.querySpec()
	_spec.Node.Columns = dcpq.ctx.Fields
	if len(dcpq.ctx.Fields) > 0 {
		_spec.Unique = dcpq.ctx.Unique != nil && *dcpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dcpq.driver, _spec)
}

func (dcpq *DivisionChoicePMQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(division_choice_pm.Table, division_choice_pm.Columns, sqlgraph.NewFieldSpec(division_choice_pm.FieldID, field.TypeInt32))
	_spec.From = dcpq.sql
	if unique := dcpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dcpq.path != nil {
		_spec.Unique = true
	}
	if fields := dcpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, division_choice_pm.FieldID)
		for i := range fields {
			if fields[i] != division_choice_pm.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if dcpq.withApplnGDSPMRef != nil {
			_spec.Node.AddColumnOnce(division_choice_pm.FieldApplicationID)
		}
	}
	if ps := dcpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dcpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dcpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dcpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dcpq *DivisionChoicePMQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dcpq.driver.Dialect())
	t1 := builder.Table(division_choice_pm.Table)
	columns := dcpq.ctx.Fields
	if len(columns) == 0 {
		columns = division_choice_pm.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dcpq.sql != nil {
		selector = dcpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dcpq.ctx.Unique != nil && *dcpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dcpq.predicates {
		p(selector)
	}
	for _, p := range dcpq.order {
		p(selector)
	}
	if offset := dcpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dcpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DivisionChoicePMGroupBy is the group-by builder for Division_Choice_PM entities.
type DivisionChoicePMGroupBy struct {
	selector
	build *DivisionChoicePMQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dcpgb *DivisionChoicePMGroupBy) Aggregate(fns ...AggregateFunc) *DivisionChoicePMGroupBy {
	dcpgb.fns = append(dcpgb.fns, fns...)
	return dcpgb
}

// Scan applies the selector query and scans the result into the given value.
func (dcpgb *DivisionChoicePMGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dcpgb.build.ctx, "GroupBy")
	if err := dcpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DivisionChoicePMQuery, *DivisionChoicePMGroupBy](ctx, dcpgb.build, dcpgb, dcpgb.build.inters, v)
}

func (dcpgb *DivisionChoicePMGroupBy) sqlScan(ctx context.Context, root *DivisionChoicePMQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dcpgb.fns))
	for _, fn := range dcpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dcpgb.flds)+len(dcpgb.fns))
		for _, f := range *dcpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dcpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dcpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DivisionChoicePMSelect is the builder for selecting fields of DivisionChoicePM entities.
type DivisionChoicePMSelect struct {
	*DivisionChoicePMQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dcps *DivisionChoicePMSelect) Aggregate(fns ...AggregateFunc) *DivisionChoicePMSelect {
	dcps.fns = append(dcps.fns, fns...)
	return dcps
}

// Scan applies the selector query and scans the result into the given value.
func (dcps *DivisionChoicePMSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dcps.ctx, "Select")
	if err := dcps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DivisionChoicePMQuery, *DivisionChoicePMSelect](ctx, dcps.DivisionChoicePMQuery, dcps, dcps.inters, v)
}

func (dcps *DivisionChoicePMSelect) sqlScan(ctx context.Context, root *DivisionChoicePMQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dcps.fns))
	for _, fn := range dcps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dcps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dcps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
