// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"recruit/ent/examtype"
	"recruit/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ExamTypeDelete is the builder for deleting a ExamType entity.
type ExamTypeDelete struct {
	config
	hooks    []Hook
	mutation *ExamTypeMutation
}

// Where appends a list predicates to the ExamTypeDelete builder.
func (etd *ExamTypeDelete) Where(ps ...predicate.ExamType) *ExamTypeDelete {
	etd.mutation.Where(ps...)
	return etd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (etd *ExamTypeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, etd.sqlExec, etd.mutation, etd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (etd *ExamTypeDelete) ExecX(ctx context.Context) int {
	n, err := etd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (etd *ExamTypeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(examtype.Table, sqlgraph.NewFieldSpec(examtype.FieldID, field.TypeInt32))
	if ps := etd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, etd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	etd.mutation.done = true
	return affected, err
}

// ExamTypeDeleteOne is the builder for deleting a single ExamType entity.
type ExamTypeDeleteOne struct {
	etd *ExamTypeDelete
}

// Where appends a list predicates to the ExamTypeDelete builder.
func (etdo *ExamTypeDeleteOne) Where(ps ...predicate.ExamType) *ExamTypeDeleteOne {
	etdo.etd.mutation.Where(ps...)
	return etdo
}

// Exec executes the deletion query.
func (etdo *ExamTypeDeleteOne) Exec(ctx context.Context) error {
	n, err := etdo.etd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{examtype.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (etdo *ExamTypeDeleteOne) ExecX(ctx context.Context) {
	if err := etdo.Exec(ctx); err != nil {
		panic(err)
	}
}
