// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"recruit/ent/exam_applications_ip"
	"recruit/ent/recommendationsipapplications"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// RecommendationsIPApplications is the model entity for the RecommendationsIPApplications schema.
type RecommendationsIPApplications struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ApplicationID holds the value of the "ApplicationID" field.
	ApplicationID int64 `json:"ApplicationID,omitempty"`
	// EmployeeID holds the value of the "EmployeeID" field.
	EmployeeID int64 `json:"EmployeeID,omitempty"`
	// ExamNameCode holds the value of the "ExamNameCode" field.
	ExamNameCode string `json:"ExamNameCode,omitempty"`
	// ExamYear holds the value of the "ExamYear" field.
	ExamYear string `json:"ExamYear,omitempty"`
	// VacancyYear holds the value of the "VacancyYear" field.
	VacancyYear int32 `json:"VacancyYear,omitempty"`
	// CARecommendations holds the value of the "CA_Recommendations" field.
	CARecommendations string `json:"CA_Recommendations,omitempty"`
	// CAUpdatedAt holds the value of the "CA_UpdatedAt" field.
	CAUpdatedAt time.Time `json:"CA_UpdatedAt,omitempty"`
	// CAUserName holds the value of the "CA_UserName" field.
	CAUserName string `json:"CA_UserName,omitempty"`
	// CARemarks holds the value of the "CA_Remarks" field.
	CARemarks string `json:"CA_Remarks,omitempty"`
	// NORecommendations holds the value of the "NO_Recommendations" field.
	NORecommendations string `json:"NO_Recommendations,omitempty"`
	// NOUpdatedAt holds the value of the "NO_UpdatedAt" field.
	NOUpdatedAt time.Time `json:"NO_UpdatedAt,omitempty"`
	// NOUserName holds the value of the "NO_UserName" field.
	NOUserName string `json:"NO_UserName,omitempty"`
	// NORemarks holds the value of the "NO_Remarks" field.
	NORemarks string `json:"NO_Remarks,omitempty"`
	// ApplicationStatus holds the value of the "ApplicationStatus" field.
	ApplicationStatus string `json:"ApplicationStatus,omitempty"`
	// UpdatedAt holds the value of the "UpdatedAt" field.
	UpdatedAt time.Time `json:"UpdatedAt,omitempty"`
	// UpdatedBy holds the value of the "UpdatedBy" field.
	UpdatedBy string `json:"UpdatedBy,omitempty"`
	// GenerateHallTicketFlag holds the value of the "GenerateHallTicketFlag" field.
	GenerateHallTicketFlag bool `json:"GenerateHallTicketFlag,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RecommendationsIPApplicationsQuery when eager-loading is set.
	Edges                                    RecommendationsIPApplicationsEdges `json:"edges"`
	exam_applications_ip_ip_applications_ref *int64
	selectValues                             sql.SelectValues
}

// RecommendationsIPApplicationsEdges holds the relations/edges for other nodes in the graph.
type RecommendationsIPApplicationsEdges struct {
	// ApplnRef holds the value of the ApplnRef edge.
	ApplnRef *Exam_Applications_IP `json:"ApplnRef,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ApplnRefOrErr returns the ApplnRef value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RecommendationsIPApplicationsEdges) ApplnRefOrErr() (*Exam_Applications_IP, error) {
	if e.loadedTypes[0] {
		if e.ApplnRef == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: exam_applications_ip.Label}
		}
		return e.ApplnRef, nil
	}
	return nil, &NotLoadedError{edge: "ApplnRef"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RecommendationsIPApplications) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case recommendationsipapplications.FieldGenerateHallTicketFlag:
			values[i] = new(sql.NullBool)
		case recommendationsipapplications.FieldID, recommendationsipapplications.FieldApplicationID, recommendationsipapplications.FieldEmployeeID, recommendationsipapplications.FieldVacancyYear:
			values[i] = new(sql.NullInt64)
		case recommendationsipapplications.FieldExamNameCode, recommendationsipapplications.FieldExamYear, recommendationsipapplications.FieldCARecommendations, recommendationsipapplications.FieldCAUserName, recommendationsipapplications.FieldCARemarks, recommendationsipapplications.FieldNORecommendations, recommendationsipapplications.FieldNOUserName, recommendationsipapplications.FieldNORemarks, recommendationsipapplications.FieldApplicationStatus, recommendationsipapplications.FieldUpdatedBy:
			values[i] = new(sql.NullString)
		case recommendationsipapplications.FieldCAUpdatedAt, recommendationsipapplications.FieldNOUpdatedAt, recommendationsipapplications.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case recommendationsipapplications.ForeignKeys[0]: // exam_applications_ip_ip_applications_ref
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RecommendationsIPApplications fields.
func (ria *RecommendationsIPApplications) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case recommendationsipapplications.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ria.ID = int64(value.Int64)
		case recommendationsipapplications.FieldApplicationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field ApplicationID", values[i])
			} else if value.Valid {
				ria.ApplicationID = value.Int64
			}
		case recommendationsipapplications.FieldEmployeeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field EmployeeID", values[i])
			} else if value.Valid {
				ria.EmployeeID = value.Int64
			}
		case recommendationsipapplications.FieldExamNameCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ExamNameCode", values[i])
			} else if value.Valid {
				ria.ExamNameCode = value.String
			}
		case recommendationsipapplications.FieldExamYear:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ExamYear", values[i])
			} else if value.Valid {
				ria.ExamYear = value.String
			}
		case recommendationsipapplications.FieldVacancyYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field VacancyYear", values[i])
			} else if value.Valid {
				ria.VacancyYear = int32(value.Int64)
			}
		case recommendationsipapplications.FieldCARecommendations:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field CA_Recommendations", values[i])
			} else if value.Valid {
				ria.CARecommendations = value.String
			}
		case recommendationsipapplications.FieldCAUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field CA_UpdatedAt", values[i])
			} else if value.Valid {
				ria.CAUpdatedAt = value.Time
			}
		case recommendationsipapplications.FieldCAUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field CA_UserName", values[i])
			} else if value.Valid {
				ria.CAUserName = value.String
			}
		case recommendationsipapplications.FieldCARemarks:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field CA_Remarks", values[i])
			} else if value.Valid {
				ria.CARemarks = value.String
			}
		case recommendationsipapplications.FieldNORecommendations:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field NO_Recommendations", values[i])
			} else if value.Valid {
				ria.NORecommendations = value.String
			}
		case recommendationsipapplications.FieldNOUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field NO_UpdatedAt", values[i])
			} else if value.Valid {
				ria.NOUpdatedAt = value.Time
			}
		case recommendationsipapplications.FieldNOUserName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field NO_UserName", values[i])
			} else if value.Valid {
				ria.NOUserName = value.String
			}
		case recommendationsipapplications.FieldNORemarks:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field NO_Remarks", values[i])
			} else if value.Valid {
				ria.NORemarks = value.String
			}
		case recommendationsipapplications.FieldApplicationStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ApplicationStatus", values[i])
			} else if value.Valid {
				ria.ApplicationStatus = value.String
			}
		case recommendationsipapplications.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field UpdatedAt", values[i])
			} else if value.Valid {
				ria.UpdatedAt = value.Time
			}
		case recommendationsipapplications.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field UpdatedBy", values[i])
			} else if value.Valid {
				ria.UpdatedBy = value.String
			}
		case recommendationsipapplications.FieldGenerateHallTicketFlag:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field GenerateHallTicketFlag", values[i])
			} else if value.Valid {
				ria.GenerateHallTicketFlag = value.Bool
			}
		case recommendationsipapplications.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field exam_applications_ip_ip_applications_ref", value)
			} else if value.Valid {
				ria.exam_applications_ip_ip_applications_ref = new(int64)
				*ria.exam_applications_ip_ip_applications_ref = int64(value.Int64)
			}
		default:
			ria.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RecommendationsIPApplications.
// This includes values selected through modifiers, order, etc.
func (ria *RecommendationsIPApplications) Value(name string) (ent.Value, error) {
	return ria.selectValues.Get(name)
}

// QueryApplnRef queries the "ApplnRef" edge of the RecommendationsIPApplications entity.
func (ria *RecommendationsIPApplications) QueryApplnRef() *ExamApplicationsIPQuery {
	return NewRecommendationsIPApplicationsClient(ria.config).QueryApplnRef(ria)
}

// Update returns a builder for updating this RecommendationsIPApplications.
// Note that you need to call RecommendationsIPApplications.Unwrap() before calling this method if this RecommendationsIPApplications
// was returned from a transaction, and the transaction was committed or rolled back.
func (ria *RecommendationsIPApplications) Update() *RecommendationsIPApplicationsUpdateOne {
	return NewRecommendationsIPApplicationsClient(ria.config).UpdateOne(ria)
}

// Unwrap unwraps the RecommendationsIPApplications entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ria *RecommendationsIPApplications) Unwrap() *RecommendationsIPApplications {
	_tx, ok := ria.config.driver.(*txDriver)
	if !ok {
		panic("ent: RecommendationsIPApplications is not a transactional entity")
	}
	ria.config.driver = _tx.drv
	return ria
}

// String implements the fmt.Stringer.
func (ria *RecommendationsIPApplications) String() string {
	var builder strings.Builder
	builder.WriteString("RecommendationsIPApplications(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ria.ID))
	builder.WriteString("ApplicationID=")
	builder.WriteString(fmt.Sprintf("%v", ria.ApplicationID))
	builder.WriteString(", ")
	builder.WriteString("EmployeeID=")
	builder.WriteString(fmt.Sprintf("%v", ria.EmployeeID))
	builder.WriteString(", ")
	builder.WriteString("ExamNameCode=")
	builder.WriteString(ria.ExamNameCode)
	builder.WriteString(", ")
	builder.WriteString("ExamYear=")
	builder.WriteString(ria.ExamYear)
	builder.WriteString(", ")
	builder.WriteString("VacancyYear=")
	builder.WriteString(fmt.Sprintf("%v", ria.VacancyYear))
	builder.WriteString(", ")
	builder.WriteString("CA_Recommendations=")
	builder.WriteString(ria.CARecommendations)
	builder.WriteString(", ")
	builder.WriteString("CA_UpdatedAt=")
	builder.WriteString(ria.CAUpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("CA_UserName=")
	builder.WriteString(ria.CAUserName)
	builder.WriteString(", ")
	builder.WriteString("CA_Remarks=")
	builder.WriteString(ria.CARemarks)
	builder.WriteString(", ")
	builder.WriteString("NO_Recommendations=")
	builder.WriteString(ria.NORecommendations)
	builder.WriteString(", ")
	builder.WriteString("NO_UpdatedAt=")
	builder.WriteString(ria.NOUpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("NO_UserName=")
	builder.WriteString(ria.NOUserName)
	builder.WriteString(", ")
	builder.WriteString("NO_Remarks=")
	builder.WriteString(ria.NORemarks)
	builder.WriteString(", ")
	builder.WriteString("ApplicationStatus=")
	builder.WriteString(ria.ApplicationStatus)
	builder.WriteString(", ")
	builder.WriteString("UpdatedAt=")
	builder.WriteString(ria.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("UpdatedBy=")
	builder.WriteString(ria.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("GenerateHallTicketFlag=")
	builder.WriteString(fmt.Sprintf("%v", ria.GenerateHallTicketFlag))
	builder.WriteByte(')')
	return builder.String()
}

// RecommendationsIPApplicationsSlice is a parsable slice of RecommendationsIPApplications.
type RecommendationsIPApplicationsSlice []*RecommendationsIPApplications
